### ISSUE TITLE
Heroku pipelines

### ISSUE THREAD

**Issue by zamith** [subvisual/subvisual.com#110]
What about deploying this to heroku as well, just so that we can use the [review apps functionality](https://blog.heroku.com/archives/2015/5/19/heroku_review_apps_beta)?

Benefits:
- No more need for printscreens on PRs
- Ability for anyone on the company to more easily provide feedback before merging
- Easier for anyone to test on different browsers before merging

**Comment by zamith** [comment]
@subvisual/developers Anyone?

**Comment by naps62** [comment]
I don't fully know how that works, but it looks interesting. Can it do the following?
1. Have a staging app, automatically deployed from master
2. Have additional apps, for each PR

If so, it would be useful, because right now I'm deploying randomly to our own staging server whenever I want to test a new branch

**Comment by pfac** [comment]
In my opinion makes sense to try this feature. If it works as well as advertised it allows designers to be included in the review process. No downsides. :+1:

**Comment by zamith** [comment]
@naps62 It does exactly that.

**Comment by ronaldofs** [comment]
Looks nice, we should try this.

**Comment by joaojusto** [comment]
Closing
